// eslint-disable-next-line no-unused-vars
const mock_data = [
  {'username':'tcastaignet0','name':'ucruttenden0','message':'sed nisl nunc rhoncus dui vel sem','msg-id':[''],'color':'#58a1c3'},
  {'username':'sfincke1','name':'aballston1','message':'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce','msg-id':[''],'color':'#419560'},
  {'username':'mperrins2','name':'tshoubridge2','message':'viverra diam vitae quam suspendisse potenti','msg-id':[''],'color':null},
  {'username':'lshearston3','name':'lwhiffen3','message':'donec dapibus duis at velit eu est congue elementum','msg-id':[''],'color':'#231f4b'},
  {'username':'nrenihan4','name':'bslemming4','message':'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam','msg-id':[''],'color':'#06b879'},
  {'username':'esoulsby5','name':'fcalderon5','message':'vel accumsan tellus nisi eu orci mauris','msg-id':['highlighted'],'color':'#89435a'},
  {'username':'hscrigmour6','name':'hbeards6','message':'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat','msg-id':['highlighted'],'color':null},
  {'username':'jtongue7','name':'golongain7','message':'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea','msg-id':[''],'color':'#438df0'},
  {'username':'mjudd8','name':'podriscoll8','message':'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum','msg-id':[''],'color':'#9b4e7e'},
  {'username':'obogie9','name':'doldacre9','message':'bibendum imperdiet nullam orci pede','msg-id':[''],'color':'#57f8e4'},
  {'username':'sdodgea','name':'lbalassia','message':'volutpat erat quisque erat eros viverra eget congue eget semper rutrum','msg-id':['highlighted'],'color':null},
  {'username':'rdmiterkob','name':'bdoylendb','message':'nullam varius nulla facilisi cras non velit','msg-id':[''],'color':'#6b52b1'},
  {'username':'sfargec','name':'ehelksc','message':'gravida nisi at nibh in hac habitasse platea dictumst','msg-id':[''],'color':'#e4e05d'},
  {'username':'gmcaleesed','name':'ksawtelld','message':'sapien cursus vestibulum proin eu mi nulla ac','msg-id':[''],'color':'#f44e1d'},
  {'username':'hgephearte','name':'tmattiessene','message':'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi','msg-id':[''],'color':'#500ed1'},
  {'username':'aaymericf','name':'kstorckf','message':'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla','msg-id':[''],'color':'#5184bb'},
  {'username':'vsambrokg','name':'cbemandg','message':'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus','msg-id':['highlighted'],'color':'#c0dc51'},
  {'username':'hsaggh','name':'dcastellh','message':'sed interdum venenatis turpis enim','msg-id':[''],'color':'#b4ef12'},
  {'username':'gmelonbyi','name':'brashleighi','message':'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus','msg-id':[''],'color':'#2e0f5d'},
  {'username':'adanterj','name':'oroydonj','message':'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam','msg-id':[''],'color':'#37d096'},
  {'username':'gwickendonk','name':'kstarkingk','message':'et eros vestibulum ac est lacinia nisi venenatis tristique fusce','msg-id':[''],'color':'#92d3ef'},
  {'username':'egarwelll','name':'gburhilll','message':'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet','msg-id':['highlighted'],'color':'#b21512'},
  {'username':'mstefanovicm','name':'mlippm','message':'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue','msg-id':[''],'color':'#ef025e'},
  {'username':'flundbeckn','name':'zthornborrown','message':'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat','msg-id':[''],'color':'#dbe3ce'},
  {'username':'cmcinteeo','name':'roliverpaullo','message':'elementum pellentesque quisque porta volutpat erat quisque erat','msg-id':[''],'color':'#ebecbf'},
  {'username':'vjambrozekp','name':'tjirousekp','message':'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus','msg-id':[''],'color':null},
  {'username':'rmorgonq','name':'jhoovartq','message':'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros','msg-id':[''],'color':'#535812'},
  {'username':'agiurior','name':'hsticklandr','message':'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam','msg-id':['highlighted'],'color':'#3789fb'},
  {'username':'spharrows','name':'fgreenhowes','message':'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede','msg-id':['highlighted'],'color':'#f1458e'},
  {'username':'jvolkest','name':'emcgraght','message':'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo','msg-id':[''],'color':'#ed80fc'},
  {'username':'lsalvatiu','name':'ebloxlandu','message':'accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec','msg-id':[''],'color':'#2ac2b6'},
  {'username':'dliccardov','name':'lartusv','message':'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula','msg-id':[''],'color':'#e0ef54'},
  {'username':'lkirsoppw','name':'rhairesnapew','message':'velit id pretium iaculis diam erat fermentum justo nec','msg-id':['highlighted'],'color':'#14073e'},
  {'username':'amadenx','name':'rpossellx','message':'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed','msg-id':[''],'color':'#ce7de6'},
  {'username':'bdennidgey','name':'tnaisbitty','message':'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed','msg-id':[''],'color':'#adb80e'},
  {'username':'fpraillz','name':'achengz','message':'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in','msg-id':[''],'color':'#9b5e87'},
  {'username':'fgillis10','name':'krout10','message':'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit','msg-id':[''],'color':null},
  {'username':'nforrestall11','name':'dtussaine11','message':'nam tristique tortor eu pede','msg-id':[''],'color':'#510bf5'},
  {'username':'ymcquirter12','name':'dcadigan12','message':'libero non mattis pulvinar nulla pede ullamcorper augue','msg-id':[''],'color':'#a53564'},
  {'username':'ldormand13','name':'gfairbard13','message':'et ultrices posuere cubilia curae duis faucibus accumsan odio','msg-id':['highlighted'],'color':null},
  {'username':'llouisot14','name':'kswoffer14','message':'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec','msg-id':[''],'color':null},
  {'username':'ysaiz15','name':'jbrockhouse15','message':'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam','msg-id':[''],'color':'#554a18'},
  {'username':'jgarfoot16','name':'wwestney16','message':'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis','msg-id':[''],'color':'#fc01ad'},
  {'username':'hbestman17','name':'fcandy17','message':'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices','msg-id':['highlighted'],'color':null},
  {'username':'iweakley18','name':'lraulin18','message':'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere','msg-id':[''],'color':'#11e206'},
  {'username':'cfeacham19','name':'smcmeekin19','message':'pede justo eu massa donec dapibus duis at velit eu est','msg-id':[''],'color':null},
  {'username':'cgoeff1a','name':'ndarlington1a','message':'augue vel accumsan tellus nisi eu orci mauris','msg-id':['highlighted'],'color':'#8df4e9'},
  {'username':'pfilpo1b','name':'taldersey1b','message':'ac nibh fusce lacus purus aliquet at','msg-id':[''],'color':'#56f282'},
  {'username':'jarmit1c','name':'wboffin1c','message':'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique','msg-id':[''],'color':null},
  {'username':'mbrafield1d','name':'apenhaleurack1d','message':'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus','msg-id':[''],'color':'#03dae2'},
  {'username':'cmorch1e','name':'mkaasmann1e','message':'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum','msg-id':[''],'color':'#4bad99'},
  {'username':'tchasen1f','name':'gburgis1f','message':'duis faucibus accumsan odio curabitur','msg-id':[''],'color':'#2b362c'},
  {'username':'apettifer1g','name':'bhaucke1g','message':'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac','msg-id':['highlighted'],'color':'#6df57c'},
  {'username':'wpleasants1h','name':'oclapperton1h','message':'arcu sed augue aliquam erat volutpat','msg-id':['highlighted'],'color':null},
  {'username':'adarville1i','name':'jfavela1i','message':'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo','msg-id':[''],'color':'#9c6b2d'},
  {'username':'lmcart1j','name':'jrief1j','message':'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac','msg-id':[''],'color':null},
  {'username':'dbaynom1k','name':'jdemange1k','message':'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus','msg-id':[''],'color':'#1108a7'},
  {'username':'ousher1l','name':'mbalassi1l','message':'non ligula pellentesque ultrices phasellus id','msg-id':['highlighted'],'color':'#ee9abb'},
  {'username':'ccurgenven1m','name':'mapfel1m','message':'duis bibendum morbi non quam nec dui luctus rutrum nulla','msg-id':[''],'color':'#4c714a'},
  {'username':'pcoalburn1n','name':'aproffer1n','message':'mauris eget massa tempor convallis nulla neque libero convallis eget','msg-id':[''],'color':'#83068f'},
  {'username':'ccrilly1o','name':'cadess1o','message':'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede','msg-id':[''],'color':'#385c48'},
  {'username':'zmagner1p','name':'kcopello1p','message':'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque','msg-id':[''],'color':null},
  {'username':'bmcgillivrie1q','name':'gsoulsby1q','message':'molestie lorem quisque ut erat curabitur gravida nisi at nibh in','msg-id':[''],'color':null},
  {'username':'tkilrow1r','name':'sbrundill1r','message':'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices','msg-id':[''],'color':'#fae411'},
  {'username':'bkincade1s','name':'bpimerick1s','message':'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non','msg-id':[''],'color':'#fd90e4'},
  {'username':'mfrossell1t','name':'flilloe1t','message':'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus','msg-id':[''],'color':'#f81b40'},
  {'username':'temmett1u','name':'dspilstead1u','message':'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo','msg-id':[''],'color':'#f3586a'},
  {'username':'rbront1v','name':'jspyby1v','message':'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta','msg-id':[''],'color':'#0f9eb1'},
  {'username':'mblythin1w','name':'cgonnet1w','message':'proin eu mi nulla ac enim in tempor turpis','msg-id':[''],'color':'#391601'},
  {'username':'vphilo1x','name':'htattoo1x','message':'erat quisque erat eros viverra eget','msg-id':[''],'color':'#dfe740'},
  {'username':'challede1y','name':'nswayne1y','message':'congue risus semper porta volutpat','msg-id':['highlighted'],'color':'#cd60d3'},
  {'username':'rcavy1z','name':'ndevanny1z','message':'libero convallis eget eleifend luctus','msg-id':[''],'color':null},
  {'username':'bforsey20','name':'lbigrigg20','message':'odio odio elementum eu interdum eu tincidunt in leo maecenas','msg-id':[''],'color':'#53ea73'},
  {'username':'ychurly21','name':'jenos21','message':'nulla ultrices aliquet maecenas leo odio','msg-id':[''],'color':'#08d725'},
  {'username':'bwear22','name':'kcicchelli22','message':'curae duis faucibus accumsan odio curabitur convallis duis consequat dui','msg-id':[''],'color':null},
  {'username':'dbute23','name':'ccorinton23','message':'luctus rutrum nulla tellus in sagittis dui vel','msg-id':['highlighted'],'color':'#bc3f95'},
  {'username':'gcahen24','name':'cmacguffog24','message':'porttitor lacus at turpis donec','msg-id':['highlighted'],'color':'#c09ee5'},
  {'username':'priping25','name':'hwalentynowicz25','message':'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum','msg-id':[''],'color':'#a240ce'},
  {'username':'ctowner26','name':'dpavlata26','message':'metus sapien ut nunc vestibulum','msg-id':[''],'color':'#b9eae4'},
  {'username':'awansbury27','name':'cdaddow27','message':'felis sed interdum venenatis turpis enim blandit','msg-id':[''],'color':'#842c4b'},
  {'username':'ffreschini28','name':'tmcginley28','message':'consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede','msg-id':[''],'color':'#9b70a4'},
  {'username':'cjanaud29','name':'tmottini29','message':'congue diam id ornare imperdiet','msg-id':['highlighted'],'color':'#feddae'},
  {'username':'kbosse2a','name':'jcrawshaw2a','message':'congue etiam justo etiam pretium iaculis justo in hac','msg-id':[''],'color':'#1d8b14'},
  {'username':'pluparto2b','name':'adonnell2b','message':'ligula nec sem duis aliquam convallis nunc proin at turpis a pede','msg-id':['highlighted'],'color':'#a4ac68'},
  {'username':'ewaight2c','name':'kspeachley2c','message':'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue','msg-id':[''],'color':'#3894f3'},
  {'username':'ywear2d','name':'aroselli2d','message':'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis','msg-id':['highlighted'],'color':'#69f110'},
  {'username':'tancliff2e','name':'bdenison2e','message':'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla','msg-id':[''],'color':'#94d7d8'},
  {'username':'bmarvel2f','name':'kdemaria2f','message':'venenatis turpis enim blandit mi in porttitor','msg-id':['highlighted'],'color':null},
  {'username':'ddemattia2g','name':'nloade2g','message':'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum','msg-id':[''],'color':'#b73978'},
  {'username':'lfranzotto2h','name':'lgarroway2h','message':'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum','msg-id':[''],'color':'#aca9e9'},
  {'username':'cgrinston2i','name':'ljirak2i','message':'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor','msg-id':[''],'color':'#74b16c'},
  {'username':'jmiddleweek2j','name':'rsavory2j','message':'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo','msg-id':[''],'color':'#147d57'},
  {'username':'jfrancello2k','name':'dmacgiollapheadair2k','message':'pretium nisl ut volutpat sapien arcu sed augue','msg-id':[''],'color':null},
  {'username':'emugford2l','name':'vspuffard2l','message':'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus','msg-id':[''],'color':'#3016a3'},
  {'username':'jdunlea2m','name':'hledwidge2m','message':'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit','msg-id':[''],'color':'#b98b54'},
  {'username':'lrennox2n','name':'govise2n','message':'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam','msg-id':[''],'color':null},
  {'username':'gvandijk2o','name':'dciciotti2o','message':'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu','msg-id':[''],'color':'#3f6b4d'},
  {'username':'mtuny2p','name':'jserraillier2p','message':'ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula','msg-id':[''],'color':'#6e4dc9'},
  {'username':'jgreenlies2q','name':'ochaperling2q','message':'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam','msg-id':['highlighted'],'color':'#c9633e'},
  {'username':'feve2r','name':'dbalwin2r','message':'aliquam erat volutpat in congue etiam justo etiam','msg-id':['highlighted'],'color':'#44abd8'},
];
